import sqlite3
from sqlite3 import Error

def conexao():
    caminho = r"C:\Users\pirsp\Documents\Torrenfut\torrenfut\db.sqlite3"
    